In [23]:
import mysql.connector
import pandas as pd

config = {
  'user': 'root',
  'password': 'root',
  'host': '127.0.0.1',
  'port': 8889,
  'database': 'job_Scapping',
  'raise_on_warnings': True
}

cnx = mysql.connector.connect(**config)

cursor = cnx.cursor(dictionary=True)

cursor.execute("SELECT * FROM `d_city`")

results = cursor.fetchall()
print(results)

df=pd.DataFrame(results)


cnx.close()

[{'id': 2296, 'city': 'Lille cedex'}, {'id': 2297, 'city': 'Chartres cedex'}, {'id': 2298, 'city': 'Annecy'}, {'id': 2299, 'city': 'LYON CEDEX 03'}, {'id': 2300, 'city': 'Metz'}, {'id': 2301, 'city': 'Châlons'}, {'id': 2302, 'city': 'Strasbourg'}, {'id': 2303, 'city': 'Châlons-en-Champagne'}, {'id': 2304, 'city': 'TOULOUSE'}, {'id': 2305, 'city': 'ROUEN'}, {'id': 2306, 'city': 'CHAVILLE'}, {'id': 2307, 'city': 'Pau cedex 9'}, {'id': 2308, 'city': 'NANTERRE CEDEX'}, {'id': 2309, 'city': 'FORT DE FRANCE CEDEX'}, {'id': 2310, 'city': 'AMIENS'}, {'id': 2311, 'city': 'RAISMES'}, {'id': 2312, 'city': 'SENS CEDEX'}, {'id': 2313, 'city': 'PARIS'}, {'id': 2314, 'city': 'NOISY LE GRAND'}, {'id': 2315, 'city': 'Quillan'}, {'id': 2316, 'city': 'RENNES'}, {'id': 2317, 'city': 'Caen'}, {'id': 2318, 'city': 'MONTAUBAN Cedex'}, {'id': 2319, 'city': 'ECROUVES'}, {'id': 2320, 'city': 'Grenoble cedex 01'}, {'id': 2321, 'city': 'POITIERS'}, {'id': 2322, 'city': 'FECAMP'}, {'id': 2323, 'city': 'BESANÇON'}, {'id': 2324, 'city': 'Haguenau'}, {'id': 2325, 'city': 'PONTCHARRA'}, {'id': 2326, 'city': 'Rouen Cedex'}, {'id': 2327, 'city': 'SAINT VINCENT DE MERCUZE'}, {'id': 2328, 'city': 'Honfleur'}, {'id': 2329, 'city': 'Melle'}, {'id': 2330, 'city': 'Montigny-Lès-Metz'}, {'id': 2331, 'city': 'CHINON'}, {'id': 2332, 'city': 'TOURY-LURCY'}, {'id': 2333, 'city': 'TECOU'}, {'id': 2334, 'city': 'Graulhet'}, {'id': 2335, 'city': 'RABASTENS'}, {'id': 2336, 'city': 'Vitry-en-artois'}, {'id': 2337, 'city': 'ROMAINVILLE'}, {'id': 2338, 'city': 'Vire'}, {'id': 2339, 'city': 'Nantes - 44'}, {'id': 2340, 'city': "Villeneuve-d'Ascq - 59"}, {'id': 2341, 'city': 'Lyon - 69'}, {'id': 2342, 'city': 'Cagnes-sur-Mer - 06'}, {'id': 2343, 'city': 'Lille - 59'}, {'id': 2344, 'city': 'Angers - 49'}, {'id': 2345, 'city': 'Dijon - 21'}, {'id': 2346, 'city': 'Rennes - 35'}, {'id': 2347, 'city': 'Mougins - 06'}, {'id': 2348, 'city': 'Alpes-Maritimes - 06'}, {'id': 2349, 'city': 'Rouffach - 68'}, {'id': 2350, 'city': 'Courbevoie - 92'}, {'id': 2351, 'city': 'Lyon 1er - Paris 1er'}, {'id': 2352, 'city': 'Nanterre - 92'}, {'id': 2353, 'city': 'Paris - 75'}, {'id': 2354, 'city': 'Toulouse - 31'}, {'id': 2355, 'city': 'Lyon 1er - 69'}, {'id': 2356, 'city': 'Lyon 9e - 69'}, {'id': 2357, 'city': 'Guyancourt - 78'}, {'id': 2358, 'city': 'Nîmes - 30'}, {'id': 2359, 'city': 'Bordeaux'}, {'id': 2360, 'city': 'Lyon'}, {'id': 2361, 'city': 'Puteaux'}, {'id': 2362, 'city': 'Issy-les-Moulineaux'}, {'id': 2363, 'city': 'Marseille · Montpellier'}, {'id': 2364, 'city': 'Paris · Lille · Nantes…'}, {'id': 2365, 'city': 'Fontenay-sous-Bois'}, {'id': 2366, 'city': 'Nantes'}, {'id': 2367, 'city': 'Montpellier'}, {'id': 2368, 'city': 'Bons-en-Chablais'}, {'id': 2369, 'city': 'Suresnes · Suresnes'}, {'id': 2370, 'city': 'La Défense'}, {'id': 2371, 'city': 'Mérignac'}, {'id': 2372, 'city': 'Ivry-sur-Seine'}, {'id': 2373, 'city': 'Tournan-en-Brie'}, {'id': 2374, 'city': 'Saint-Cloud'}, {'id': 2375, 'city': 'Paris · Paris'}, {'id': 2376, 'city': 'Moirans'}, {'id': 2377, 'city': 'Nice'}, {'id': 2378, 'city': 'Massy'}, {'id': 2379, 'city': "Villeneuve-d'Ascq"}, {'id': 2380, 'city': 'Nanterre'}, {'id': 2381, 'city': 'Paris · Paris · Paris'}, {'id': 2382, 'city': 'Grenoble'}, {'id': 2383, 'city': 'Paris · Bordeaux'}, {'id': 2384, 'city': 'Gennevilliers'}]

In [24]:
pd.set_option('display.max_rows', None)

In [25]:
df

      id                      city
0   2296               Lille cedex
1   2297            Chartres cedex
2   2298                    Annecy
3   2299             LYON CEDEX 03
4   2300                      Metz
5   2301                   Châlons
6   2302                Strasbourg
7   2303      Châlons-en-Champagne
8   2304                  TOULOUSE
9   2305                     ROUEN
10  2306                  CHAVILLE
11  2307               Pau cedex 9
12  2308            NANTERRE CEDEX
13  2309      FORT DE FRANCE CEDEX
14  2310                    AMIENS
15  2311                   RAISMES
16  2312                SENS CEDEX
17  2313                     PARIS
18  2314            NOISY LE GRAND
19  2315                   Quillan
20  2316                    RENNES
21  2317                      Caen
22  2318           MONTAUBAN Cedex
23  2319                  ECROUVES
24  2320         Grenoble cedex 01
25  2321                  POITIERS
26  2322                    FECAMP
27  2323                  BESANÇON
28  2324                  Haguenau
29  2325                PONTCHARRA
30  2326               Rouen Cedex
31  2327  SAINT VINCENT DE MERCUZE
32  2328                  Honfleur
33  2329                     Melle
34  2330         Montigny-Lès-Metz
35  2331                    CHINON
36  2332               TOURY-LURCY
37  2333                     TECOU
38  2334                  Graulhet
39  2335                 RABASTENS
40  2336           Vitry-en-artois
41  2337               ROMAINVILLE
42  2338                      Vire
43  2339               Nantes - 44
44  2340    Villeneuve-d'Ascq - 59
45  2341                 Lyon - 69
46  2342       Cagnes-sur-Mer - 06
47  2343                Lille - 59
48  2344               Angers - 49
49  2345                Dijon - 21
50  2346               Rennes - 35
51  2347              Mougins - 06
52  2348      Alpes-Maritimes - 06
53  2349             Rouffach - 68
54  2350           Courbevoie - 92
55  2351      Lyon 1er - Paris 1er
56  2352             Nanterre - 92
57  2353                Paris - 75
58  2354             Toulouse - 31
59  2355             Lyon 1er - 69
60  2356              Lyon 9e - 69
61  2357           Guyancourt - 78
62  2358                Nîmes - 30
63  2359                  Bordeaux
64  2360                      Lyon
65  2361                   Puteaux
66  2362       Issy-les-Moulineaux
67  2363   Marseille · Montpellier
68  2364   Paris · Lille · Nantes…
69  2365        Fontenay-sous-Bois
70  2366                    Nantes
71  2367               Montpellier
72  2368          Bons-en-Chablais
73  2369       Suresnes · Suresnes
74  2370                La Défense
75  2371                  Mérignac
76  2372            Ivry-sur-Seine
77  2373           Tournan-en-Brie
78  2374               Saint-Cloud
79  2375             Paris · Paris
80  2376                   Moirans
81  2377                      Nice
82  2378                     Massy
83  2379         Villeneuve-d'Ascq
84  2380                  Nanterre
85  2381     Paris · Paris · Paris
86  2382                  Grenoble
87  2383          Paris · Bordeaux
88  2384             Gennevilliers

In [34]:
df["city"]=df["city"].str.replace("cedex", '', case=False)
df["city"]=df["city"].str.replace('\d+', '', regex=True)
df["city"]=df["city"].str.replace(r'\s+er\s+', ' ', regex=True)
df["city"]=df["city"].str.replace(r'\s+-\s+', ' ', regex=True)
df["city"]=df["city"].str.replace(r'\s+e\s+', ' ', regex=True)
df["city"]=df["city"].str.replace('La Défense', 'Paris ',case=False)
df["city"]=df["city"].str.replace('Lyon Paris er', 'Paris ',case=False)


df["city"]=df["city"].str.split('·').str[0]
df

      id                      city
0   2296                    Lille
1   2297                 Chartres
2   2298                    Annecy
3   2299                    LYON
4   2300                      Metz
5   2301                   Châlons
6   2302                Strasbourg
7   2303      Châlons-en-Champagne
8   2304                  TOULOUSE
9   2305                     ROUEN
10  2306                  CHAVILLE
11  2307                     Pau
12  2308                 NANTERRE
13  2309           FORT DE FRANCE
14  2310                    AMIENS
15  2311                   RAISMES
16  2312                     SENS
17  2313                     PARIS
18  2314            NOISY LE GRAND
19  2315                   Quillan
20  2316                    RENNES
21  2317                      Caen
22  2318                MONTAUBAN
23  2319                  ECROUVES
24  2320                Grenoble
25  2321                  POITIERS
26  2322                    FECAMP
27  2323                  BESANÇON
28  2324                  Haguenau
29  2325                PONTCHARRA
30  2326                    Rouen
31  2327  SAINT VINCENT DE MERCUZE
32  2328                  Honfleur
33  2329                     Melle
34  2330         Montigny-Lès-Metz
35  2331                    CHINON
36  2332               TOURY-LURCY
37  2333                     TECOU
38  2334                  Graulhet
39  2335                 RABASTENS
40  2336           Vitry-en-artois
41  2337               ROMAINVILLE
42  2338                      Vire
43  2339                   Nantes
44  2340        Villeneuve-d'Ascq
45  2341                     Lyon
46  2342           Cagnes-sur-Mer
47  2343                    Lille
48  2344                   Angers
49  2345                    Dijon
50  2346                   Rennes
51  2347                  Mougins
52  2348          Alpes-Maritimes
53  2349                 Rouffach
54  2350               Courbevoie
55  2351                    Paris
56  2352                 Nanterre
57  2353                    Paris
58  2354                 Toulouse
59  2355                     Lyon
60  2356                     Lyon
61  2357               Guyancourt
62  2358                    Nîmes
63  2359                  Bordeaux
64  2360                      Lyon
65  2361                   Puteaux
66  2362       Issy-les-Moulineaux
67  2363                Marseille
68  2364                    Paris
69  2365        Fontenay-sous-Bois
70  2366                    Nantes
71  2367               Montpellier
72  2368          Bons-en-Chablais
73  2369                 Suresnes
74  2370                    Paris
75  2371                  Mérignac
76  2372            Ivry-sur-Seine
77  2373           Tournan-en-Brie
78  2374               Saint-Cloud
79  2375                    Paris
80  2376                   Moirans
81  2377                      Nice
82  2378                     Massy
83  2379         Villeneuve-d'Ascq
84  2380                  Nanterre
85  2381                    Paris
86  2382                  Grenoble
87  2383                    Paris
88  2384             Gennevilliers

In [35]:
# import pandas as pd
# import geopandas as gpd
# from geopy.geocoders import Nominatim
# import matplotlib.pyplot as plt

# # Exemple de dataframe avec des noms de villes en France
# data = df.city
# df = pd.DataFrame(data)

# # Fonction pour obtenir les coordonnées géographiques (latitude, longitude) d'une ville
# def get_coordinates(city):
#     geolocator = Nominatim(user_agent="city_mapper")
#     location = geolocator.geocode(city + ", France")
#     if location:
#         return location.latitude, location.longitude
#     else:
#         return None

# Ajouter une colonne 'Coordinates' au dataframe avec les coordonnées de chaque ville
# df['Coordinates'] = df['Ville'].apply(get_coordinates)

# # Supprimer les lignes avec des coordonnées manquantes
# df = df.dropna(subset=['Coordinates'])

# # Créer un GeoDataFrame à partir du dataframe
# gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df['Coordinates'].apply(lambda x: x[1]), df['Coordinates'].apply(lambda x: x[0])))

# # Charger la carte de la France avec geopandas
# france = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
# france = france[france.name == "France"]

# # Afficher la carte de la France avec les points pour chaque ville
# ax = france.plot(figsize=(10, 8), color='white', edgecolor='black')

# # Ajouter les points des villes au tracé
# gdf.plot(ax=ax, color='red', marker='o', markersize=100)

# # Ajouter les noms des villes comme étiquettes
# for x, y, label in zip(gdf.geometry.x, gdf.geometry.y, gdf['Ville']):
#     ax.text(x, y, label, fontsize=8)

# # Afficher la carte
# plt.show()

In [40]:
for i in df.itertuples():
    print(i)
    get_coordinates(i.city)

Pandas(Index=0, id=2296, city='Lille ')
Pandas(Index=1, id=2297, city='Chartres ')
Pandas(Index=2, id=2298, city='Annecy')
Pandas(Index=3, id=2299, city='LYON  ')
Pandas(Index=4, id=2300, city='Metz')
Pandas(Index=5, id=2301, city='Châlons')
Pandas(Index=6, id=2302, city='Strasbourg')
Pandas(Index=7, id=2303, city='Châlons-en-Champagne')
Pandas(Index=8, id=2304, city='TOULOUSE')
Pandas(Index=9, id=2305, city='ROUEN')
Pandas(Index=10, id=2306, city='CHAVILLE')
Pandas(Index=11, id=2307, city='Pau  ')
Pandas(Index=12, id=2308, city='NANTERRE ')
Pandas(Index=13, id=2309, city='FORT DE FRANCE ')
Pandas(Index=14, id=2310, city='AMIENS')
Pandas(Index=15, id=2311, city='RAISMES')
Pandas(Index=16, id=2312, city='SENS ')
Pandas(Index=17, id=2313, city='PARIS')
Pandas(Index=18, id=2314, city='NOISY LE GRAND')
Pandas(Index=19, id=2315, city='Quillan')
Pandas(Index=20, id=2316, city='RENNES')
Pandas(Index=21, id=2317, city='Caen')
Pandas(Index=22, id=2318, city='MONTAUBAN ')
Pandas(Index=23, id=2319, city='ECROUVES')
Pandas(Index=24, id=2320, city='Grenoble  ')
Pandas(Index=25, id=2321, city='POITIERS')
Pandas(Index=26, id=2322, city='FECAMP')
Pandas(Index=27, id=2323, city='BESANÇON')
Pandas(Index=28, id=2324, city='Haguenau')
Pandas(Index=29, id=2325, city='PONTCHARRA')
Pandas(Index=30, id=2326, city='Rouen ')
Pandas(Index=31, id=2327, city='SAINT VINCENT DE MERCUZE')
Pandas(Index=32, id=2328, city='Honfleur')
Pandas(Index=33, id=2329, city='Melle')
Pandas(Index=34, id=2330, city='Montigny-Lès-Metz')
Pandas(Index=35, id=2331, city='CHINON')
Pandas(Index=36, id=2332, city='TOURY-LURCY')
Pandas(Index=37, id=2333, city='TECOU')
Pandas(Index=38, id=2334, city='Graulhet')
Pandas(Index=39, id=2335, city='RABASTENS')
Pandas(Index=40, id=2336, city='Vitry-en-artois')
Pandas(Index=41, id=2337, city='ROMAINVILLE')
Pandas(Index=42, id=2338, city='Vire')
Pandas(Index=43, id=2339, city='Nantes ')
Pandas(Index=44, id=2340, city="Villeneuve-d'Ascq ")
Pandas(Index=45, id=2341, city='Lyon ')
Pandas(Index=46, id=2342, city='Cagnes-sur-Mer ')
Pandas(Index=47, id=2343, city='Lille ')
Pandas(Index=48, id=2344, city='Angers ')
Pandas(Index=49, id=2345, city='Dijon ')
Pandas(Index=50, id=2346, city='Rennes ')
Pandas(Index=51, id=2347, city='Mougins ')
Pandas(Index=52, id=2348, city='Alpes-Maritimes ')
Pandas(Index=53, id=2349, city='Rouffach ')
Pandas(Index=54, id=2350, city='Courbevoie ')
Pandas(Index=55, id=2351, city='Paris ')
Pandas(Index=56, id=2352, city='Nanterre ')
Pandas(Index=57, id=2353, city='Paris ')
Pandas(Index=58, id=2354, city='Toulouse ')
Pandas(Index=59, id=2355, city='Lyon ')
Pandas(Index=60, id=2356, city='Lyon ')
Pandas(Index=61, id=2357, city='Guyancourt ')
Pandas(Index=62, id=2358, city='Nîmes ')
Pandas(Index=63, id=2359, city='Bordeaux')
Pandas(Index=64, id=2360, city='Lyon')
Pandas(Index=65, id=2361, city='Puteaux')
Pandas(Index=66, id=2362, city='Issy-les-Moulineaux')
Pandas(Index=67, id=2363, city='Marseille ')
Pandas(Index=68, id=2364, city='Paris ')
Pandas(Index=69, id=2365, city='Fontenay-sous-Bois')
Pandas(Index=70, id=2366, city='Nantes')
Pandas(Index=71, id=2367, city='Montpellier')
Pandas(Index=72, id=2368, city='Bons-en-Chablais')
Pandas(Index=73, id=2369, city='Suresnes ')
Pandas(Index=74, id=2370, city='Paris ')
Pandas(Index=75, id=2371, city='Mérignac')
Pandas(Index=76, id=2372, city='Ivry-sur-Seine')
Pandas(Index=77, id=2373, city='Tournan-en-Brie')
Pandas(Index=78, id=2374, city='Saint-Cloud')
Pandas(Index=79, id=2375, city='Paris ')
Pandas(Index=80, id=2376, city='Moirans')
Pandas(Index=81, id=2377, city='Nice')
Pandas(Index=82, id=2378, city='Massy')
Pandas(Index=83, id=2379, city="Villeneuve-d'Ascq")
Pandas(Index=84, id=2380, city='Nanterre')
Pandas(Index=85, id=2381, city='Paris ')
Pandas(Index=86, id=2382, city='Grenoble')
Pandas(Index=87, id=2383, city='Paris ')
Pandas(Index=88, id=2384, city='Gennevilliers')

In [36]:
get_coordinates("NOISY LE GRAND")

(48.8478586, 2.5529612)

In [42]:
list(df.city)

['Lille ',
 'Chartres ',
 'Annecy',
 'LYON  ',
 'Metz',
 'Châlons',
 'Strasbourg',
 'Châlons-en-Champagne',
 'TOULOUSE',
 'ROUEN',
 'CHAVILLE',
 'Pau  ',
 'NANTERRE ',
 'FORT DE FRANCE ',
 'AMIENS',
 'RAISMES',
 'SENS ',
 'PARIS',
 'NOISY LE GRAND',
 'Quillan',
 'RENNES',
 'Caen',
 'MONTAUBAN ',
 'ECROUVES',
 'Grenoble  ',
 'POITIERS',
 'FECAMP',
 'BESANÇON',
 'Haguenau',
 'PONTCHARRA',
 'Rouen ',
 'SAINT VINCENT DE MERCUZE',
 'Honfleur',
 'Melle',
 'Montigny-Lès-Metz',
 'CHINON',
 'TOURY-LURCY',
 'TECOU',
 'Graulhet',
 'RABASTENS',
 'Vitry-en-artois',
 'ROMAINVILLE',
 'Vire',
 'Nantes ',
 "Villeneuve-d'Ascq ",
 'Lyon ',
 'Cagnes-sur-Mer ',
 'Lille ',
 'Angers ',
 'Dijon ',
 'Rennes ',
 'Mougins ',
 'Alpes-Maritimes ',
 'Rouffach ',
 'Courbevoie ',
 'Paris ',
 'Nanterre ',
 'Paris ',
 'Toulouse ',
 'Lyon ',
 'Lyon ',
 'Guyancourt ',
 'Nîmes ',
 'Bordeaux',
 'Lyon',
 'Puteaux',
 'Issy-les-Moulineaux',
 'Marseille ',
 'Paris ',
 'Fontenay-sous-Bois',
 'Nantes',
 'Montpellier',
 'Bons-en-Chablais',
 'Suresnes ',
 'Paris ',
 'Mérignac',
 'Ivry-sur-Seine',
 'Tournan-en-Brie',
 'Saint-Cloud',
 'Paris ',
 'Moirans',
 'Nice',
 'Massy',
 "Villeneuve-d'Ascq",
 'Nanterre',
 'Paris ',
 'Grenoble',
 'Paris ',
 'Gennevilliers']

In [44]:
import pandas as pd
import folium
from geopy.geocoders import Nominatim

# Exemple de dataframe avec des noms de villes en France
data = {'Ville':list(df.city)}
dfs = pd.DataFrame(data)

# Fonction pour obtenir les coordonnées géographiques (latitude, longitude) d'une ville
def get_coordinates(city):
    geolocator = Nominatim(user_agent="city_mapper")
    location = geolocator.geocode(city + ", France")
    if location:
        return location.latitude, location.longitude
    else:
        return None

# Ajouter une colonne 'Coordinates' au dataframe avec les coordonnées de chaque ville
dfs['Coordinates'] = dfs['Ville'].apply(get_coordinates)

# Supprimer les lignes avec des coordonnées manquantes
dfs = dfs.dropna(subset=['Coordinates'])

# Créer une carte Folium centrée sur la France
map_france = folium.Map(location=[46.603354, 1.888334], zoom_start=6)

# Ajouter des marqueurs pour chaque ville
for index, row in dfs.iterrows():
    folium.Marker(location=row['Coordinates'], popup=row['Ville']).add_to(map_france)

# Sauvegarder la carte dans un fichier HTML
map_france.save('map_france.html')